//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISClient.HelloWorldService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Learninghard.com", ConfigurationName="HelloWorldService.HellworldService")]
    public interface HellworldService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Learninghard.com/HellworldService/GetHelloWord", ReplyAction="http://www.Learninghard.com/HellworldService/GetHelloWordResponse")]
        string GetHelloWord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Learninghard.com/HellworldService/GetHelloWord", ReplyAction="http://www.Learninghard.com/HellworldService/GetHelloWordResponse")]
        System.Threading.Tasks.Task<string> GetHelloWordAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HellworldServiceChannel : IISClient.HelloWorldService.HellworldService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HellworldServiceClient : System.ServiceModel.ClientBase<IISClient.HelloWorldService.HellworldService>, IISClient.HelloWorldService.HellworldService {
        
        public HellworldServiceClient() {
        }
        
        public HellworldServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HellworldServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HellworldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HellworldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHelloWord() {
            return base.Channel.GetHelloWord();
        }
        
        public System.Threading.Tasks.Task<string> GetHelloWordAsync() {
            return base.Channel.GetHelloWordAsync();
        }
    }
}
